### ISSUE TITLE
Mule artifacts

### ISSUE THREAD

**Issue by pkasson** [mule-lint/mule-lint#11]
Is it possible to get the flow artifacts - name, sub flow, steps, etc, using the Mule Lint library ?  

So, how hard would it be to have a call into the groovy code to return this data ... since you are already capturing it for your analysis ?

Thanks

**Comment by cgorshing** [comment]
Is it possible - absolutely, but at some point this library won't have any added value if it passes each XML construct across to client code. At that point it is acting more like an xml parser than anything.

That being said, can you give more details on what you are thinking?

i.e. If you are wanting to get the flow name to perform your own validation of the name, then what else would you want? The file name as well? The full path or just the file name?

I'm going to close https://github.com/Nuisto/mule-lint-maven-plugin/issues/2 as that is only about the maven-plugin, this project is where all the features lie.

**Comment by pkasson** [comment]
I want to perform analysis across several projects - catalog artifacts - what flows / sub flows / components.  One reason is to find violations - naming standards, etc.  Look for things like 'somewhere we had a routine that did ...'.    So need to get not just high level (flow name, step name) but the attributes therein.  Can also be used for documenting projects and static analysis in general, and with custom rules

**Comment by cgorshing** [comment]
"So need to get not just high level (flow name, step name) but the attributes therein .... with custom rules" --- What are you thoughts on how this would be handed off to you (the caller)? I would assume you would want some kind of groovy scripting environment to perform the custom validation logic right?

**Comment by pkasson** [comment]
Yes, attributes as well - things that allow for a way to inventory these artifacts.  There could be a callback so that any custom rules can further validate, filter or otherwise analyze the results.

**Comment by pkasson** [comment]
Do you think it would simple enough to do this ?  I would be willing to help if I could get direction.

**Comment by cgorshing** [comment]
When running mule-lint we would need to have some kind of spring config type of file to describe what "aggregators" to allocate and pass around. I would need to figure out what the API would look like though (ie. do we have callbacks for flow begin/end, element begin end ..etc).

You lose me on the "inventory these artifacts", because that doesn't seem to fit into the "linting" way.

Naming conventions has been requested by me by a few different people (email and DMs), and I'm thinking that might be my next thing I tackle (see #12 for more info on the approach I'm thinking).

**Comment by cgorshing** [comment]
Let me know if this is something you would still like.
