### ISSUE TITLE
Github Action?

### ISSUE THREAD

**Issue by jcam** [mule-lint/mule-lint#29]
Have you considered adding a Github Action?
It could be as simple as a docker container that starts from groovy, adds mule-lint, then runs the gradlew command as the CMD.

This would allow adding your mule lint check as a simple plug in for any github repository!

**Comment by cgorshing** [comment]
I have not considered it, I'll look into it.

**Comment by cgorshing** [comment]
This is preliminary work and still needs some loving, but I have a github action working at https://github.com/mule-lint/example-mule-lint-and-github-action

I need to kick the wheels on this more and make sure all is okay, work on the docs ...etc. But wanted to ping ya about it since you mentioned it to me first.

**Comment by jcam** [comment]
Excellent! I may give this a try for one of our test repos. Thank you!!

**Comment by cgorshing** [comment]
Closing this for now, if we need other things then we can open a new issue.
